name: Code Style

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:
  gofmt:
    name: check gofmt
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.20'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: chainguard-dev/actions/gofmt@e6364567e59cb42c49cf69f8e1242f247bc23844 # main
        with:
          args: -s

  goimports:
    name: check goimports
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.20'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: chainguard-dev/actions/goimports@main # main
